### ISSUE TITLE
Doesn't work on windows

### ISSUE THREAD

**Issue by bluecanarybe** [amenzhinsky/go-memexec#1]
Hi, I've tried embedding an exe file in my go binary, but it doesn't seem to work to execute that exe file in memory. Any advice?

**Comment by amenzhinsky** [comment]
Hi, unfortunately I don't have a windows machine around. 

Anyway what error are you getting?

**Comment by bluecanarybe** [comment]
I’m trying to execute [SharpHound.exe](https://github.com/BloodHoundAD/SharpHound3) in my go binary using the following code:

First I’ll use `go-bindata -o binaries.go binaries` to embed SharpHound.exe in my ./binaries folder in my go program.

Then I’ll use following code to execute it:

```
SharpHound, err := Asset(“binaries/SharpHound.exe“)
if err != nil {
	return err
}

exe, err := memexec.New(SharpHound)
if err != nil {
	return err
}
defer exe.Close()

cmd := exe.Command() // runs without arguments
cmd.Output()
```
Am I doing anything wrong?

**Comment by amenzhinsky** [comment]
```
b, err := cmd.CombinedOutput()
if err != nil {
	// what's the error value?
}
```

**Comment by bluecanarybe** [comment]
Apologie, I'm not sure where the CombinedOutput() should be declared ?

**Comment by amenzhinsky** [comment]
Just after you initialize `cmd := exe.Command()`

**Comment by lanybass** [comment]
> ```
> b, err := cmd.CombinedOutput()
> if err != nil {
> 	// what's the error value?
> }
> ```

"C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\go-memexec-112079703": file does not exist

**Comment by lanybass** [comment]
so.. memexec is fake?
dump the binary to disk then run it. delete it at last , that's memexec?

**Comment by amenzhinsky** [comment]
I'm not sure why this happens, unfortunately I don't have a windows machine.

In essence yes, binary loaders are very complicated piece of software this is the most straightforward way to implement one.

**Comment by whoraks** [comment]
> so.. memexec is fake?
> dump the binary to disk then run it. delete it at last , that's memexec?

Would you like to change it to this one?
(memexec.go)

* before 
```
// New creates new memory execution object that can be
// used for executing commands on a memory based binary.
func New(b []byte) (*Exec, error) {
	f, err := ioutil.TempFile("", "go-memexec-")
	if err != nil {
		return nil, err
```
* after (add exe file extension)
```
// New creates new memory execution object that can be
// used for executing commands on a memory based binary.
func New(b []byte) (*Exec, error) {
	f, err := ioutil.TempFile("", "go-memexec-*.exe")
	if err != nil {
		return nil, err
```

**Comment by amenzhinsky** [comment]
@whoraks can you try the latest master?

**Comment by whoraks** [comment]
> @whoraks can you try the latest master?

Works fine in my environment: WINDOWS 10 Home (20H2) 19042.906
```
# go get github.com/amenzhinsky/go-memexec@master
go: downloading github.com/amenzhinsky/go-memexec v0.3.1-0.20210404102315-40de27353318
go get: upgraded github.com/amenzhinsky/go-memexec v0.3.0 => v0.3.1-0.20210404102315-40de27353318
```

**Comment by amenzhinsky** [comment]
https://github.com/amenzhinsky/go-memexec/releases/tag/v0.4.0

**Comment by 0xE232FE** [comment]
You can use Go 1.16+ "embed" instead of go-bindata
```
import (
    "embed"
)
```
